source 'https://rubygems.org'

gem 'rails', '4.0.4'

gem 'pg'
gem 'rabl', github: 'nesquena/rabl'
gem 'oj'
gem 'slim'
gem 'puma'
gem 'bcrypt'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'coffee-script'

group :development, :test do
  gem 'rspec-rails', '2.13.1'
  gem 'capybara'
  gem 'rack_session_access'
  gem 'launchy'
  gem 'fabrication'
  gem 'faker'
  gem 'database_cleaner'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'guard'
  gem 'guard-rspec'
  gem 'rb-fsevent'
end